<?php
$statusMeta = [
    'open' => ['Berjalan', 35, 'bg-amber-50 text-orange-600'],
    'submitted' => ['Menunggu Review', 75, 'bg-blue-50 text-blue-600'],
    'approved' => ['Selesai', 100, 'bg-green-50 text-green-600'],
    'rejected' => ['Perlu Revisi', 55, 'bg-red-50 text-red-600'],
];
[$statusLabel, $taskProgress, $statusTone] = $statusMeta[$task['status']] ?? [$task['status'], 0, 'bg-slate-100 text-slate-600'];
$deadlineDays = (int)ceil((strtotime($task['deadline_at']) - time()) / 86400);
$isOverdue = $task['status'] !== 'approved' && $deadlineDays < 0;
if ($isOverdue) [$statusLabel, $statusTone] = ['Terlambat', 'bg-red-50 text-red-600'];
if ($task['status'] === 'approved' || $deadlineDays > 7) [$priority, $priorityTone] = ['Low', 'bg-blue-50 text-blue-600'];
elseif ($deadlineDays > 3) [$priority, $priorityTone] = ['Medium', 'bg-amber-50 text-amber-600'];
else [$priority, $priorityTone] = ['High', 'bg-red-50 text-red-600'];
$latestUpdate = $task['updated_at'] ?: $task['created_at'];
?>
<main class="task-detail-page min-h-screen flex-1 overflow-x-hidden p-4 lg:p-6">
 <header class="mb-5 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
  <div><h1 class="text-[28px] font-black tracking-tight">Task Detail</h1><p class="mt-1 text-sm text-slate-500">Detail tugas project</p><p class="mt-3 text-xs text-slate-500"><a href="<?= e(app_url('index.php?page=dashboard')) ?>">Dashboard</a><span class="mx-2">/</span><a class="text-blue-600" href="<?= e(app_url('index.php?page=tasks')) ?>">Tasks</a><span class="mx-2">/</span>Task Detail</p></div>
  <div class="flex items-center gap-3"><form class="hidden min-w-[360px] items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 lg:flex" action="<?= e(app_url('index.php')) ?>"><input type="hidden" name="page" value="tasks"><svg class="h-5 w-5 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input class="w-full border-0 bg-transparent text-xs outline-none" name="q" placeholder="Cari project, tugas, atau pengguna..."></form><a class="dashboard-interactive-icon grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white" href="<?= e(app_url('index.php?page=notifications')) ?>"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Zm-8 13h4"/></svg></a><span class="grid h-10 w-10 place-items-center rounded-full bg-orange-100 font-black text-orange-600"><?= e(strtoupper(substr($user['name'],0,1))) ?></span><span class="hidden sm:block"><b class="block text-xs"><?= e($user['name']) ?></b><small class="text-slate-500"><?= e(role_label($user['role'])) ?></small></span></div>
 </header>
 <?php if($taskError): ?><div class="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700"><?= e($taskError) ?></div><?php endif; ?><?php if($taskSuccess): ?><div class="mb-4 rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-bold text-green-700"><?= e($taskSuccess) ?></div><?php endif; ?>
 <div class="grid gap-5 xl:grid-cols-[minmax(0,2.5fr)_minmax(300px,.95fr)]">
  <div class="space-y-5">
   <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div class="flex flex-col gap-5 lg:flex-row lg:items-start">
     <span class="grid h-16 w-16 shrink-0 place-items-center rounded-full bg-orange-100 text-orange-600"><svg class="h-8 w-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M9 5H6v16h12V5h-3M9 3h6v4H9z"/><path d="m9 14 2 2 4-5"/></svg></span>
     <div class="min-w-0 flex-1"><h2 class="text-xl font-black"><?= e($task['title']) ?></h2><div class="mt-4 grid gap-4 text-xs sm:grid-cols-2 xl:grid-cols-5"><div><span class="block text-slate-500">Project</span><a class="mt-1 block font-bold text-blue-600" href="<?= e(app_url('actions/project-detail.php?id='.$task['project_id'])) ?>"><?= e($task['project_title']) ?></a></div><div><span class="block text-slate-500">Assignee</span><b class="mt-1 block truncate"><?= e($currentAssignees[0]['name'] ?? '-') ?></b></div><div><span class="block text-slate-500">Status</span><span class="mt-1 inline-block rounded-md px-2 py-1 font-bold <?= e($statusTone) ?>"><?= e($statusLabel) ?></span></div><div><span class="block text-slate-500">Prioritas</span><span class="mt-1 inline-block rounded-md px-2 py-1 font-bold <?= e($priorityTone) ?>"><?= e($priority) ?></span></div><div><span class="block text-slate-500">Deadline</span><b class="mt-1 block"><?= e(date('d M Y',strtotime($task['deadline_at']))) ?></b><small class="<?= $isOverdue?'text-red-600':'text-orange-600' ?>"><?= $task['status']==='approved'?'Selesai':($isOverdue?e(abs($deadlineDays)).' hari terlambat':e(max(0,$deadlineDays)).' hari lagi') ?></small></div></div></div>
     <div class="grid shrink-0 place-items-center"><span class="task-detail-ring grid h-20 w-20 place-items-center rounded-full" style="--progress:<?= e($taskProgress) ?>"><span class="grid h-14 w-14 place-items-center rounded-full bg-white font-black"><?= e($taskProgress) ?>%</span></span><small class="mt-2 text-slate-500">Progress</small></div>
    </div>
    <div class="mt-5 flex flex-wrap gap-3"><?php if($canSubmitTask): ?><button class="open-submit-modal rounded-xl bg-orange-600 px-5 py-3 text-sm font-black text-white" type="button">Submit Bukti Pekerjaan</button><?php endif; ?><button class="focus-comment rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold" type="button">Tambah Komentar</button><?php if($canEditTask && !task_has_locked_review($pdo,$taskId)): ?><button class="open-edit-task rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold" type="button">Edit Task</button><?php endif; ?><?php if($canReviewTask && $hasSubmittedProof): ?><button class="open-review-modal rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white" type="button">Review Bukti</button><?php endif; ?><?php if($canReviewTask && $task['status']==='approved'): ?><button class="open-reopen-modal rounded-xl bg-red-50 px-5 py-3 text-sm font-black text-red-700" type="button">Buka Ulang Task</button><?php endif; ?></div>
   </section>
   <section class="grid gap-5 lg:grid-cols-2">
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">1. Deskripsi Tugas</h3><p class="mt-5 min-h-[76px] text-sm leading-6 text-slate-600"><?= nl2br(e($task['description'] ?: 'Tidak ada deskripsi task.')) ?></p><div class="mt-5 grid gap-3 border-t border-slate-100 pt-4 text-xs sm:grid-cols-3"><span><small class="block text-slate-400">Dibuat oleh</small><b><?= e($task['creator_name']) ?></b></span><span><small class="block text-slate-400">Tanggal Dibuat</small><b><?= e(date('d M Y, H:i',strtotime($task['created_at']))) ?></b></span><span><small class="block text-slate-400">Terakhir Diperbarui</small><b><?= e(date('d M Y, H:i',strtotime($latestUpdate))) ?></b></span></div></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">2. Progress / Checklist</h3><div class="mt-4 divide-y divide-slate-100 text-xs"><?php $steps=[['Task dibuat',true,25],['Bukti pekerjaan dikirim',count($subs)>0,75],['Review selesai',$task['status']==='approved',100]]; foreach($steps as [$label,$done,$pct]): ?><div class="flex items-center gap-3 py-3"><span class="grid h-5 w-5 place-items-center rounded-full border-2 <?= $done?'border-green-500 text-green-600':'border-slate-300 text-slate-300' ?>"><?= $done?'✓':'' ?></span><b class="flex-1"><?= e($label) ?></b><span class="text-slate-500"><?= $done?'Selesai':'Belum Mulai' ?></span><b><?= $done?e($pct):0 ?>%</b></div><?php endforeach; ?></div><div class="mt-4 flex items-center gap-4 border-t border-slate-100 pt-4 text-xs"><span>Total Progress</span><span class="h-2 flex-1 rounded-full bg-slate-100"><i class="task-detail-progress block h-2 rounded-full bg-orange-500" style="width:<?= e($taskProgress) ?>%"></i></span><b><?= e($taskProgress) ?>%</b></div></article>
   </section>
   <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">3. Lampiran / Bukti Pekerjaan</h3><div class="mt-3 divide-y divide-slate-100 text-xs"><?php foreach($subs as $s): ?><div class="grid items-center gap-3 py-3 md:grid-cols-[1.4fr_1fr_1fr_auto]"><span><b class="block"><?= e($s['file_path']?basename($s['file_path']):'Catatan bukti pekerjaan') ?></b><small class="text-slate-400"><?= e($s['note']) ?></small></span><span><?= e($s['submitter_name']) ?></span><span><?= e(date('d M Y, H:i',strtotime($s['created_at']))) ?></span><?php if($s['file_path']): ?><a class="font-bold text-blue-600" href="<?= e(app_url($s['file_path'])) ?>" target="_blank">Buka File</a><?php else: ?><span>-</span><?php endif; ?></div><?php endforeach; ?><?php if(!$subs): ?><p class="py-8 text-center text-slate-500">Belum ada bukti pekerjaan.</p><?php endif; ?></div></section>
   <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">4. Komentar / Diskusi</h3><div class="mt-3 divide-y divide-slate-100"><?php foreach($comments as $comment): $canDeleteComment=(int)$comment['user_id']===(int)$user['id']||$user['role']==='SUPERADMIN'||$canReviewTask; ?><div class="flex gap-3 py-3"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-orange-100 text-xs font-black text-orange-600"><?= e(strtoupper(substr($comment['name'],0,1))) ?></span><span class="min-w-0 flex-1"><b class="text-xs"><?= e($comment['name']) ?></b><small class="ml-2 text-[10px] text-slate-400"><?= e(role_label($comment['role'])) ?></small><p class="mt-1 text-xs text-slate-600"><?= e($comment['body']) ?></p></span><small class="whitespace-nowrap text-[10px] text-slate-400"><?= e(date('d M Y, H:i',strtotime($comment['created_at']))) ?></small><?php if($canDeleteComment): ?><form method="post" action="<?= e(app_url('actions/task-comment.php')) ?>" onsubmit="return confirm('Hapus komentar ini?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete_comment"><input type="hidden" name="task_id" value="<?= e($taskId) ?>"><input type="hidden" name="comment_id" value="<?= e($comment['id']) ?>"><button class="text-[10px] font-bold text-red-600">Hapus</button></form><?php endif; ?></div><?php endforeach; ?></div><form class="mt-3 flex gap-2" method="post" action="<?= e(app_url('actions/task-comment.php')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="add_comment"><input type="hidden" name="task_id" value="<?= e($taskId) ?>"><input id="taskCommentInput" class="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-xs" name="body" placeholder="Tulis komentar Anda..." required><button class="rounded-xl bg-slate-900 px-5 text-xs font-black text-white">Kirim</button></form></section>
  </div>
  <aside class="space-y-5">
   <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">Ringkasan Tugas</h3><div class="mt-5 space-y-5 text-xs"><div><small class="text-slate-400">Project</small><a class="mt-1 block font-black text-blue-600" href="<?= e(app_url('actions/project-detail.php?id='.$task['project_id'])) ?>"><?= e($task['project_title']) ?></a></div><div><small class="text-slate-400">Manager</small><b class="mt-1 block"><?= e($task['creator_name']) ?></b></div><div><small class="text-slate-400">Anggota Tim</small><div class="mt-2 flex -space-x-2"><?php foreach(array_slice($projectMembers,0,5) as $member): ?><span class="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-orange-100 text-[10px] font-black text-orange-600" title="<?= e($member['name']) ?>"><?= e(strtoupper(substr($member['name'],0,1))) ?></span><?php endforeach; ?><?php if(count($projectMembers)>5): ?><span class="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-slate-100 text-[10px] font-black">+<?= e(count($projectMembers)-5) ?></span><?php endif; ?></div></div><div class="space-y-3 border-t border-slate-100 pt-4"><p class="flex justify-between"><span>Tanggal Mulai</span><b><?= e(date('d M Y',strtotime($task['created_at']))) ?></b></p><p class="flex justify-between"><span>Deadline</span><b><?= e(date('d M Y',strtotime($task['deadline_at']))) ?></b></p><p class="flex justify-between"><span>Status</span><b><?= e($statusLabel) ?></b></p><p class="flex justify-between"><span>Prioritas</span><b><?= e($priority) ?></b></p></div></div></section>
   <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black">Pengingat / Aktivitas Terbaru</h3><div class="mt-4 divide-y divide-slate-100"><?php foreach($taskActivities as $activity): ?><div class="flex gap-3 py-3"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-green-100 text-green-600">✓</span><span class="min-w-0 flex-1"><b class="block text-xs"><?= e($activity['name']) ?></b><small class="block text-slate-500"><?= e($activity['action']) ?></small></span><small class="whitespace-nowrap text-[10px] text-slate-400"><?= e(date('d M H:i',strtotime($activity['created_at']))) ?></small></div><?php endforeach; ?><?php if(!$taskActivities): ?><p class="py-8 text-center text-xs text-slate-500">Belum ada aktivitas.</p><?php endif; ?></div></section>
  </aside>
 </div>
</main>
<?php if($canSubmitTask): ?><div class="submit-task-modal fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><form class="task-detail-modal w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl" method="post" action="<?= e(app_url('actions/task-submit.php')) ?>" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="task_id" value="<?= e($taskId) ?>"><div class="flex justify-between"><h3 class="text-xl font-black">Submit Bukti Pekerjaan</h3><button class="close-submit-modal text-2xl" type="button">×</button></div><textarea class="mt-5 w-full rounded-xl border border-slate-200 p-4" name="note" rows="4" placeholder="Catatan pekerjaan..." required></textarea><input class="mt-4 w-full rounded-xl border border-slate-200 p-3" name="proof_file" type="file"><button class="mt-5 w-full rounded-xl bg-orange-600 px-5 py-3 font-black text-white">Kirim Bukti</button></form></div><?php endif; ?>
<?php if($canReviewTask && $hasSubmittedProof): ?><div class="review-task-modal fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><form class="task-detail-modal w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl" method="post" action="<?= e(app_url('actions/task-review.php')) ?>"><?= csrf_field() ?><input type="hidden" name="task_id" value="<?= e($taskId) ?>"><div class="flex justify-between"><h3 class="text-xl font-black">Review Bukti Pekerjaan</h3><button class="close-review-modal text-2xl" type="button">×</button></div><textarea class="mt-5 w-full rounded-xl border border-slate-200 p-4" name="review_note" rows="4" placeholder="Catatan review atau alasan revisi"></textarea><div class="mt-5 flex gap-3"><button class="flex-1 rounded-xl bg-green-600 px-5 py-3 font-black text-white" name="decision" value="approved">Verified Checked</button><button class="flex-1 rounded-xl bg-red-600 px-5 py-3 font-black text-white" name="decision" value="rejected">Reject</button></div></form></div><?php endif; ?>
<?php if($canEditTask && !task_has_locked_review($pdo,$taskId)): ?><div class="edit-task-modal fixed inset-0 z-50 <?= $taskError?'flex':'hidden' ?> items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><form class="task-detail-modal max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="update_task"><div class="flex justify-between"><h3 class="text-xl font-black">Edit Task</h3><button class="close-edit-task text-2xl" type="button">×</button></div><input class="mt-5 w-full rounded-xl border border-slate-200 px-4 py-3" name="title" value="<?= e($task['title']) ?>" required><textarea class="mt-4 w-full rounded-xl border border-slate-200 p-4" name="description" rows="3"><?= e($task['description']) ?></textarea><input class="mt-4 w-full rounded-xl border border-slate-200 px-4 py-3" type="datetime-local" name="deadline_at" value="<?= e(date('Y-m-d\TH:i',strtotime($task['deadline_at']))) ?>" required><div class="mt-4 grid gap-2 md:grid-cols-2"><?php foreach($editableAssignees as $candidate): ?><label class="flex gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" name="assignee_ids[]" value="<?= e($candidate['id']) ?>" <?= in_array((int)$candidate['id'],$currentAssigneeIds,true)?'checked':'' ?>><span><b class="block text-sm"><?= e($candidate['name']) ?></b><small><?= e($candidate['role']) ?></small></span></label><?php endforeach; ?></div><button class="mt-5 w-full rounded-xl bg-orange-600 px-5 py-3 font-black text-white">Simpan Task</button></form></div><?php endif; ?>
<?php if($canReviewTask && $task['status']==='approved'): ?><div class="reopen-task-modal fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><form class="task-detail-modal w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="reopen_task"><div class="flex justify-between"><h3 class="text-xl font-black">Buka Ulang Task</h3><button class="close-reopen-modal text-2xl" type="button">×</button></div><input class="mt-5 w-full rounded-xl border border-slate-200 px-4 py-3" name="reason" placeholder="Alasan task dibuka ulang" required><button class="mt-5 w-full rounded-xl bg-red-600 px-5 py-3 font-black text-white">Buka Ulang Task</button></form></div><?php endif; ?>
<script>(()=>{const bind=(open,modal,close)=>{const panel=document.querySelector(modal);document.querySelectorAll(open).forEach(b=>b.addEventListener('click',()=>{panel?.classList.remove('hidden');panel?.classList.add('flex')}));document.querySelectorAll(close).forEach(b=>b.addEventListener('click',()=>{panel?.classList.add('hidden');panel?.classList.remove('flex')}));panel?.addEventListener('click',e=>{if(e.target===panel){panel.classList.add('hidden');panel.classList.remove('flex')}})};bind('.open-submit-modal','.submit-task-modal','.close-submit-modal');bind('.open-review-modal','.review-task-modal','.close-review-modal');bind('.open-edit-task','.edit-task-modal','.close-edit-task');bind('.open-reopen-modal','.reopen-task-modal','.close-reopen-modal');document.querySelectorAll('.focus-comment').forEach(b=>b.addEventListener('click',()=>document.getElementById('taskCommentInput')?.focus()));requestAnimationFrame(()=>document.querySelectorAll('.task-detail-progress').forEach(b=>b.classList.add('is-ready')))})();</script>
