<?php
$statusMeta = [
    'open' => ['Berjalan', 35, 'bg-amber-50 text-orange-600'],
    'submitted' => ['Menunggu Review', 100, 'bg-amber-50 text-orange-600'],
    'approved' => ['Selesai', 100, 'bg-green-50 text-green-600'],
    'rejected' => ['Perlu Revisi', 55, 'bg-red-50 text-red-600'],
];
[$statusLabel, $taskProgress, $statusTone] = $statusMeta[$task['status']] ?? [$task['status'], 0, 'bg-slate-100 text-slate-600'];
$deadlineDays = (int)ceil((strtotime($task['deadline_at']) - time()) / 86400);
$isOverdue = $task['status'] !== 'approved' && $deadlineDays < 0;
if ($isOverdue) [$statusLabel, $statusTone] = ['Terlambat', 'bg-red-50 text-red-600'];
if ($task['status'] === 'approved' || $deadlineDays > 7) [$priority, $priorityTone] = ['Rendah', 'bg-green-50 text-green-600'];
elseif ($deadlineDays > 3) [$priority, $priorityTone] = ['Sedang', 'bg-amber-50 text-amber-600'];
else [$priority, $priorityTone] = ['Mendesak', 'bg-red-50 text-red-600'];
$latestSubmission = $subs[0] ?? null;
$reviewerName = $latestSubmission['reviewer_name'] ?? ($canReviewTask ? $user['name'] : $task['creator_name']);
$reviewerRole = $canReviewTask ? role_label($user['role']) : 'Project Manager';
?>
<main class="task-review-page min-h-screen flex-1 overflow-x-hidden p-4 lg:p-6">
 <header class="task-review-header">
  <div><p><a href="<?= e(app_url('index.php?page=dashboard')) ?>">Dashboard</a><span>/</span><a href="<?= e(app_url('index.php?page=tasks')) ?>">Task</a><span>/</span>Review & Approval</p><h1>Task Review / Approval</h1><small>Tinjau hasil pekerjaan dan berikan persetujuan atau minta revisi.</small></div>
  <div><a href="<?= e(app_url('index.php?page=tasks&project_id='.$task['project_id'])) ?>">Kembali ke Task</a><?php if($canEditTask&&!task_has_locked_review($pdo,$taskId)): ?><button class="open-edit-task" type="button">Edit Task</button><?php endif; ?></div>
 </header>
 <?php if($taskError): ?><div class="task-review-alert is-error"><?= e($taskError) ?></div><?php endif; ?><?php if($taskSuccess): ?><div class="task-review-alert is-success"><?= e($taskSuccess) ?></div><?php endif; ?>

 <section class="task-review-summary">
  <div><small>Task</small><b><?= e($task['title']) ?></b><span>#TASK-<?= e(str_pad((string)$taskId,5,'0',STR_PAD_LEFT)) ?></span></div>
  <div><small>Project</small><a href="<?= e(app_url('actions/project-detail.php?id='.$task['project_id'])) ?>"><?= e($task['project_title']) ?></a><span><?= e($task['description'] ?: 'Project aktif') ?></span></div>
  <div><small>Assignee</small><b class="task-review-person"><i><?= e(strtoupper(substr($currentAssignees[0]['name']??'-',0,1))) ?></i><?= e($currentAssignees[0]['name']??'-') ?></b><span><?= e(count($currentAssignees)) ?> penerima task</span></div>
  <div><small>Prioritas</small><b class="task-review-priority <?= e($priorityTone) ?>"><?= e($priority) ?></b></div>
  <div><small>Deadline</small><b><?= e(date('d M Y',strtotime($task['deadline_at']))) ?></b><span class="<?= $isOverdue?'text-red-600':'' ?>"><?= $task['status']==='approved'?'Selesai':($isOverdue?e(abs($deadlineDays)).' hari terlambat':e(max(0,$deadlineDays)).' hari lagi') ?></span></div>
  <div><small>Status</small><b class="task-review-status <?= e($statusTone) ?>"><?= e($statusLabel) ?></b></div>
  <div><small>Progress</small><span class="task-review-progress"><i style="width:<?= e($taskProgress) ?>%"></i></span><b><?= e($taskProgress) ?>%</b></div>
 </section>

 <div class="task-review-layout">
  <section class="task-review-workspace">
   <nav class="task-review-tabs"><button class="is-active" data-review-tab="submission">Detail Submission</button><button data-review-tab="description">Deskripsi Task</button><button data-review-tab="history">Riwayat</button><button data-review-tab="attachments">Lampiran</button><button data-review-tab="comments">Diskusi</button></nav>
   <div class="task-review-panel is-active" data-review-panel="submission">
    <div class="task-review-submission-grid">
     <div>
      <article class="task-review-card"><h2>Informasi Submission</h2><?php if($latestSubmission): ?><dl><div><dt>Tanggal Dikumpulkan</dt><dd><?= e(date('d M Y, H:i',strtotime($latestSubmission['created_at']))) ?></dd></div><div><dt>Dikumpulkan Oleh</dt><dd><?= e($latestSubmission['submitter_name']) ?></dd></div><div><dt>Catatan Pengumpulan</dt><dd><?= e($latestSubmission['note'] ?: 'Tidak ada catatan.') ?></dd></div></dl><?php else: ?><p class="task-review-empty">Belum ada submission untuk task ini.</p><?php endif; ?></article>
      <article class="task-review-card task-review-preview"><h2>Preview Hasil Pekerjaan</h2><?php if($latestSubmission&&$latestSubmission['file_path']): ?><div><span>File bukti pekerjaan siap ditinjau</span><b><?= e(basename($latestSubmission['file_path'])) ?></b><small>Preview langsung mengikuti jenis file yang diunggah.</small></div><a href="<?= e(app_url($latestSubmission['file_path'])) ?>" target="_blank">Buka di Tab Baru</a><?php else: ?><p class="task-review-empty">Submission belum memiliki file bukti.</p><?php endif; ?></article>
     </div>
     <div>
      <article class="task-review-card"><h2>File & Deliverable</h2><div class="task-review-files"><?php foreach($subs as $s): ?><div><i><?= $s['file_path']?'FILE':'NOTE' ?></i><span><b><?= e($s['file_path']?basename($s['file_path']):'Catatan submission') ?></b><small><?= e(date('d M Y, H:i',strtotime($s['created_at']))) ?></small></span><?php if($s['file_path']): ?><a href="<?= e(app_url($s['file_path'])) ?>" target="_blank">Buka</a><?php endif; ?></div><?php endforeach; ?><?php if(!$subs): ?><p class="task-review-empty">Belum ada deliverable.</p><?php endif; ?></div></article>
      <article class="task-review-card"><h2>Checklist Workflow</h2><ul class="task-review-checklist"><li class="is-done">Task telah dibuat</li><li class="<?= $subs?'is-done':'' ?>">Bukti pekerjaan dikirim</li><li class="<?= $task['status']==='submitted'?'is-done':'' ?>">Menunggu keputusan reviewer</li><li class="<?= $task['status']==='approved'?'is-done':'' ?>">Review disetujui</li></ul></article>
     </div>
    </div>
   </div>
   <div class="task-review-panel" data-review-panel="description"><article class="task-review-card"><h2>Deskripsi Task</h2><p class="task-review-copy"><?= nl2br(e($task['description'] ?: 'Tidak ada deskripsi task.')) ?></p><dl><div><dt>Dibuat oleh</dt><dd><?= e($task['creator_name']) ?></dd></div><div><dt>Dibuat pada</dt><dd><?= e(date('d M Y, H:i',strtotime($task['created_at']))) ?></dd></div></dl></article></div>
   <div class="task-review-panel" data-review-panel="history"><article class="task-review-card"><h2>Riwayat Submit & Review</h2><div class="task-review-history"><?php foreach($subs as $s): ?><div><span class="<?= e($s['status']) ?>"><?= e(get_task_status_label($s['status'])) ?></span><b><?= e($s['submitter_name']) ?></b><small><?= e(date('d M Y, H:i',strtotime($s['created_at']))) ?></small><p><?= e($s['review_note'] ?: $s['note']) ?></p></div><?php endforeach; ?><?php if(!$subs): ?><p class="task-review-empty">Belum ada riwayat submission.</p><?php endif; ?></div></article></div>
   <div class="task-review-panel" data-review-panel="attachments"><article class="task-review-card"><h2>Semua Lampiran</h2><div class="task-review-files"><?php foreach($subs as $s): if(!$s['file_path'])continue; ?><div><i>FILE</i><span><b><?= e(basename($s['file_path'])) ?></b><small><?= e($s['submitter_name']) ?></small></span><a href="<?= e(app_url($s['file_path'])) ?>" target="_blank">Buka</a></div><?php endforeach; ?></div></article></div>
   <div class="task-review-panel" data-review-panel="comments"><article class="task-review-card"><h2>Diskusi Task</h2><div class="task-review-comments"><?php foreach($comments as $comment): ?><div><i><?= e(strtoupper(substr($comment['name'],0,1))) ?></i><span><b><?= e($comment['name']) ?></b><small><?= e(date('d M Y, H:i',strtotime($comment['created_at']))) ?></small><p><?= e($comment['body']) ?></p></span></div><?php endforeach; ?></div><form method="post" action="<?= e(app_url('actions/task-comment.php')) ?>"><input type="hidden" name="action" value="add_comment"><input type="hidden" name="task_id" value="<?= e($taskId) ?>"><?= csrf_field() ?><input id="taskCommentInput" name="body" placeholder="Tulis komentar..." required><button>Kirim</button></form></article></div>
   <footer class="task-review-note">Setelah review dikirim, assignee akan menerima notifikasi dan dapat melihat feedback pada riwayat task.</footer>
  </section>

  <aside class="task-review-aside">
   <section><h2>Reviewer</h2><div class="task-review-reviewer"><i><?= e(strtoupper(substr($reviewerName,0,1))) ?></i><span><b><?= e($reviewerName) ?></b><small><?= e($reviewerRole) ?></small></span></div></section>
   <?php if($canReviewTask&&$hasSubmittedProof): ?><form method="post" action="<?= e(app_url('actions/task-review.php')) ?>" class="task-review-decision"><?= csrf_field() ?><input type="hidden" name="task_id" value="<?= e($taskId) ?>"><h3>Keputusan Review <b>*</b></h3><div><label><input type="radio" name="decision" value="approved" required><span class="approve"><b>Setujui</b><small>Terima hasil kerja</small></span></label><label><input type="radio" name="decision" value="rejected" required><span class="revise"><b>Minta Revisi</b><small>Perlu perbaikan</small></span></label></div><label class="task-review-note-field"><b>Catatan untuk Assignee</b><textarea name="review_note" rows="7" placeholder="Tulis catatan review di sini..."></textarea><small>Wajib diisi ketika meminta revisi.</small></label><button type="submit">Kirim Review</button></form><?php else: ?><section class="task-review-unavailable"><h3>Keputusan Review</h3><p><?= $canReviewTask?'Belum ada bukti submit yang menunggu review.':'Role kamu tidak memiliki akses untuk mereview task ini.' ?></p></section><?php endif; ?>
   <?php if($canSubmitTask): ?><button class="open-submit-modal task-review-submit" type="button">Submit Bukti Pekerjaan</button><?php endif; ?><?php if($canReviewTask&&$task['status']==='approved'): ?><button class="open-reopen-modal task-review-reopen" type="button">Buka Ulang Task</button><?php endif; ?>
  </aside>
 </div>
</main>
<?php if($canSubmitTask): ?><div class="submit-task-modal fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><form class="task-detail-modal w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl" method="post" action="<?= e(app_url('actions/task-submit.php')) ?>" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="task_id" value="<?= e($taskId) ?>"><div class="flex justify-between"><h3 class="text-xl font-black">Submit Bukti Pekerjaan</h3><button class="close-submit-modal text-2xl" type="button">×</button></div><textarea class="mt-5 w-full rounded-xl border border-slate-200 p-4" name="note" rows="4" placeholder="Catatan pekerjaan..." required></textarea><input class="mt-4 w-full rounded-xl border border-slate-200 p-3" name="proof_file" type="file"><button class="mt-5 w-full rounded-xl bg-orange-600 px-5 py-3 font-black text-white">Kirim Bukti</button></form></div><?php endif; ?>
<?php if($canEditTask&&!task_has_locked_review($pdo,$taskId)): ?><div class="edit-task-modal fixed inset-0 z-50 <?= $taskError?'flex':'hidden' ?> items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><form class="task-detail-modal max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="update_task"><div class="flex justify-between"><h3 class="text-xl font-black">Edit Task</h3><button class="close-edit-task text-2xl" type="button">×</button></div><input class="mt-5 w-full rounded-xl border border-slate-200 px-4 py-3" name="title" value="<?= e($task['title']) ?>" required><textarea class="mt-4 w-full rounded-xl border border-slate-200 p-4" name="description" rows="3"><?= e($task['description']) ?></textarea><input class="mt-4 w-full rounded-xl border border-slate-200 px-4 py-3" type="datetime-local" name="deadline_at" value="<?= e(date('Y-m-d\TH:i',strtotime($task['deadline_at']))) ?>" required><div class="mt-4 grid gap-2 md:grid-cols-2"><?php foreach($editableAssignees as $candidate): ?><label class="flex gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" name="assignee_ids[]" value="<?= e($candidate['id']) ?>" <?= in_array((int)$candidate['id'],$currentAssigneeIds,true)?'checked':'' ?>><span><b class="block text-sm"><?= e($candidate['name']) ?></b><small><?= e($candidate['role']) ?></small></span></label><?php endforeach; ?></div><button class="mt-5 w-full rounded-xl bg-orange-600 px-5 py-3 font-black text-white">Simpan Task</button></form></div><?php endif; ?>
<?php if($canReviewTask&&$task['status']==='approved'): ?><div class="reopen-task-modal fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><form class="task-detail-modal w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="reopen_task"><div class="flex justify-between"><h3 class="text-xl font-black">Buka Ulang Task</h3><button class="close-reopen-modal text-2xl" type="button">×</button></div><input class="mt-5 w-full rounded-xl border border-slate-200 px-4 py-3" name="reason" placeholder="Alasan task dibuka ulang" required><button class="mt-5 w-full rounded-xl bg-red-600 px-5 py-3 font-black text-white">Buka Ulang Task</button></form></div><?php endif; ?>
<script>(()=>{const tabs=document.querySelectorAll('[data-review-tab]'),panels=document.querySelectorAll('[data-review-panel]');tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.toggle('is-active',x===t));panels.forEach(p=>p.classList.toggle('is-active',p.dataset.reviewPanel===t.dataset.reviewTab))}));const reviewForm=document.querySelector('.task-review-decision'),reviewNote=reviewForm?.querySelector('[name=review_note]');reviewForm?.querySelectorAll('[name=decision]').forEach(input=>input.addEventListener('change',()=>{if(reviewNote)reviewNote.required=input.value==='rejected'}));const bind=(open,modal,close)=>{const panel=document.querySelector(modal);document.querySelectorAll(open).forEach(b=>b.addEventListener('click',()=>{panel?.classList.remove('hidden');panel?.classList.add('flex')}));document.querySelectorAll(close).forEach(b=>b.addEventListener('click',()=>{panel?.classList.add('hidden');panel?.classList.remove('flex')}));panel?.addEventListener('click',e=>{if(e.target===panel){panel.classList.add('hidden');panel.classList.remove('flex')}})};bind('.open-submit-modal','.submit-task-modal','.close-submit-modal');bind('.open-edit-task','.edit-task-modal','.close-edit-task');bind('.open-reopen-modal','.reopen-task-modal','.close-reopen-modal')})();</script>
