<?php
$user=current_user();$month=max(1,min(12,(int)($_GET['month']??date('n'))));$year=max(2020,min(2100,(int)($_GET['year']??date('Y'))));$requestedView=$_GET['view']??'month';$view=in_array($requestedView,['month','week','list'],true)?$requestedView:'month';$requestedFilter=$_GET['filter']??'all';$filter=in_array($requestedFilter,['all','open','submitted','approved','rejected'],true)?$requestedFilter:'all';
$first=sprintf('%04d-%02d-01',$year,$month);$last=date('Y-m-t',strtotime($first));$days=(int)date('t',strtotime($first));$start=(int)date('N',strtotime($first));$prev=strtotime('-1 month',strtotime($first));$next=strtotime('+1 month',strtotime($first));
$scope=$user['role']==='SUPERADMIN'?'1=1':'(pm.user_id=? OR ta.user_id=?)';$params=$user['role']==='SUPERADMIN'?[]:[$user['id'],$user['id']];$statusSql=$filter==='all'?'':' AND t.status=?';if($filter!=='all')$params[]=$filter;
$stmt=$pdo->prepare("SELECT DISTINCT t.id,t.title,t.deadline_at,t.status,p.title project_title FROM tasks t JOIN projects p ON p.id=t.project_id LEFT JOIN project_members pm ON pm.project_id=p.id LEFT JOIN task_assignees ta ON ta.task_id=t.id WHERE {$scope}{$statusSql} AND t.deleted_at IS NULL AND DATE(t.deadline_at) BETWEEN ? AND ? ORDER BY t.deadline_at");$stmt->execute(array_merge($params,[$first,$last]));$events=$stmt->fetchAll();$byDay=[];foreach($events as $event)$byDay[(int)date('j',strtotime($event['deadline_at']))][]=$event;
$todayEvents=array_values(array_filter($events,fn($e)=>date('Y-m-d',strtotime($e['deadline_at']))===date('Y-m-d')));$upcoming=array_values(array_filter($events,fn($e)=>strtotime($e['deadline_at'])>=strtotime('today')));$weekEnd=strtotime('+6 days',strtotime('today'));$weekEvents=array_values(array_filter($events,fn($e)=>strtotime($e['deadline_at'])>=strtotime('today')&&strtotime($e['deadline_at'])<=$weekEnd));
$calendarUrl=fn(array $changes=[])=>app_url('index.php?'.http_build_query(array_merge(['page'=>'calendar','month'=>$month,'year'=>$year,'view'=>$view,'filter'=>$filter],$changes)));
?>
<div class="additional-page calendar-page">
 <header class="additional-page-header"><div><p>Calendar</p><h2>Calendar</h2><span>Pantau deadline, milestone, dan jadwal review project.</span></div><div><a href="<?= e(app_url('index.php?page=tasks&create=1')) ?>">+ Tambah Jadwal</a><a href="<?= e(app_url('actions/calendar-export.php?month='.$month.'&year='.$year.'&filter='.$filter)) ?>">Export Calendar</a></div></header>
 <section class="calendar-toolbar"><a href="<?= e($calendarUrl(['month'=>date('n',$prev),'year'=>date('Y',$prev)])) ?>">&lsaquo;</a><b><?= e(date('F Y',strtotime($first))) ?></b><a href="<?= e($calendarUrl(['month'=>date('n',$next),'year'=>date('Y',$next)])) ?>">&rsaquo;</a><a href="<?= e($calendarUrl(['month'=>date('n'),'year'=>date('Y')])) ?>">Hari Ini</a><?php foreach(['month'=>'Month','week'=>'Week','list'=>'List'] as $key=>$label):?><a class="<?= $view===$key?'active':'' ?>" href="<?= e($calendarUrl(['view'=>$key])) ?>"><?= e($label) ?></a><?php endforeach;?></section>
 <nav class="calendar-filters"><?php foreach(['all'=>'Semua','open'=>'Task','submitted'=>'Review','approved'=>'Selesai','rejected'=>'Perlu Revisi'] as $key=>$label):?><a class="<?= $filter===$key?'active':'' ?>" href="<?= e($calendarUrl(['filter'=>$key])) ?>"><?= e($label) ?></a><?php endforeach;?></nav>
 <section class="calendar-layout">
  <article class="additional-card calendar-grid <?= $view!=='month'?'calendar-hidden':'' ?>"><header><?php foreach(['Sen','Sel','Rab','Kam','Jum','Sab','Min'] as $day):?><b><?= e($day) ?></b><?php endforeach;?></header><div><?php for($blank=1;$blank<$start;$blank++):?><span class="calendar-day muted"></span><?php endfor;?><?php for($day=1;$day<=$days;$day++):?><span class="calendar-day <?= date('Y-m-d')===sprintf('%04d-%02d-%02d',$year,$month,$day)?'today':'' ?>"><b><?= e($day) ?></b><?php foreach(array_slice($byDay[$day]??[],0,3) as $event):?><a class="calendar-event <?= e($event['status']) ?>" href="<?= e(app_url('actions/task-detail.php?id='.$event['id'])) ?>"><?= e($event['title']) ?><small><?= e(date('H:i',strtotime($event['deadline_at']))) ?></small></a><?php endforeach;?></span><?php endfor;?></div></article>
  <?php if($view!=='month'): $viewEvents=$view==='week'?$weekEvents:$events;?><article class="additional-card calendar-list"><header><h3><?= $view==='week'?'Agenda 7 Hari Ke Depan':'Agenda Bulan Ini' ?></h3><span><?= e(count($viewEvents)) ?> event</span></header><?php foreach($viewEvents as $event):?><a href="<?= e(app_url('actions/task-detail.php?id='.$event['id'])) ?>"><time><b><?= e(date('d',strtotime($event['deadline_at']))) ?></b><small><?= e(date('M',strtotime($event['deadline_at']))) ?></small></time><span><b><?= e($event['title']) ?></b><small><?= e($event['project_title']) ?> · <?= e(date('H:i',strtotime($event['deadline_at']))) ?></small></span><?= status_badge($event['status']) ?></a><?php endforeach;?><?php if(!$viewEvents):?><div class="additional-empty"><i>⌕</i><h3>Agenda Kosong</h3><p>Tidak ada event yang sesuai filter.</p><a href="<?= e($calendarUrl(['filter'=>'all'])) ?>">Reset Filter</a></div><?php endif;?></article><?php endif;?>
  <aside><section class="additional-card calendar-mini"><h3><?= e(date('F Y',strtotime($first))) ?></h3><p><?php for($d=1;$d<=$days;$d++):?><i class="<?= isset($byDay[$d])?'has-event':'' ?>"><?= e($d) ?></i><?php endfor;?></p></section><section class="additional-card calendar-upcoming"><h3>Event Hari Ini</h3><?php foreach($todayEvents as $event):?><a href="<?= e(app_url('actions/task-detail.php?id='.$event['id'])) ?>"><i></i><span><b><?= e($event['title']) ?></b><small><?= e($event['project_title']) ?></small></span><time><?= e(date('H:i',strtotime($event['deadline_at']))) ?></time></a><?php endforeach;?><?php if(!$todayEvents):?><p class="calendar-note">Tidak ada event hari ini.</p><?php endif;?></section><section class="additional-card calendar-upcoming"><h3>Deadline Terdekat</h3><?php foreach(array_slice($upcoming,0,5) as $event):?><a href="<?= e(app_url('actions/task-detail.php?id='.$event['id'])) ?>"><i></i><span><b><?= e($event['title']) ?></b><small><?= e($event['project_title']) ?></small></span><time><?= e(date('d M',strtotime($event['deadline_at']))) ?></time></a><?php endforeach;?><?php if(!$upcoming):?><p class="calendar-note">Tidak ada deadline mendatang.</p><?php endif;?></section><section class="additional-card calendar-legend"><h3>Legend</h3><p><i class="open"></i>Open <i class="submitted"></i>Review <i class="approved"></i>Selesai <i class="rejected"></i>Revisi</p></section></aside>
 </section>
 <a class="additional-fab" href="<?= e(app_url('index.php?page=tasks&create=1')) ?>">+</a>
</div>
