<?php
$user=current_user();
$scope=$user['role']==='SUPERADMIN'?'1=1':'p.id IN (SELECT project_id FROM project_members WHERE user_id = ?)';
$scopeParams=$user['role']==='SUPERADMIN'?[]:[$user['id']];
$from=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['from']??'')?$_GET['from']:date('Y-m-01',strtotime('-5 months'));$to=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['to']??'')?$_GET['to']:date('Y-m-d');if($from>$to){[$from,$to]=[$to,$from];}$fromDate=$from.' 00:00:00';$toDate=$to.' 23:59:59';
$stmt=$pdo->prepare("SELECT COUNT(DISTINCT p.id) projects,COUNT(DISTINCT t.id) tasks,SUM(t.status='approved') completed,SUM(t.deadline_at<NOW() AND t.status<>'approved') overdue FROM projects p LEFT JOIN tasks t ON t.project_id=p.id AND t.deleted_at IS NULL AND t.created_at BETWEEN ? AND ? WHERE {$scope} AND p.deleted_at IS NULL");$stmt->execute(array_merge([$fromDate,$toDate],$scopeParams));$summary=$stmt->fetch()?:[];
$projects=(int)($summary['projects']??0);$tasks=(int)($summary['tasks']??0);$completed=(int)($summary['completed']??0);$overdue=(int)($summary['overdue']??0);$rate=$tasks?(int)round($completed/$tasks*100):0;
if($user['role']==='SUPERADMIN'){$stmt=$pdo->query("SELECT COUNT(*) FROM users WHERE status='active' AND deleted_at IS NULL");}else{$stmt=$pdo->prepare("SELECT COUNT(DISTINCT pm.user_id) FROM project_members pm JOIN projects p ON p.id=pm.project_id JOIN users u ON u.id=pm.user_id WHERE p.id IN (SELECT project_id FROM project_members WHERE user_id=?) AND p.deleted_at IS NULL AND u.status='active' AND u.deleted_at IS NULL");$stmt->execute([$user['id']]);}$activeUsers=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT p.id,p.title,u.name manager,COUNT(t.id) total,SUM(t.status='approved') completed,SUM(t.deadline_at<NOW() AND t.status<>'approved') overdue FROM projects p JOIN users u ON u.id=p.owner_id LEFT JOIN tasks t ON t.project_id=p.id AND t.deleted_at IS NULL AND t.created_at BETWEEN ? AND ? WHERE {$scope} AND p.deleted_at IS NULL GROUP BY p.id ORDER BY overdue DESC,total DESC LIMIT 8");$stmt->execute(array_merge([$fromDate,$toDate],$scopeParams));$performance=$stmt->fetchAll();
$statusCounts=['open'=>0,'submitted'=>0,'approved'=>0,'rejected'=>0];$stmt=$pdo->prepare("SELECT t.status,COUNT(*) total FROM tasks t JOIN projects p ON p.id=t.project_id WHERE {$scope} AND t.deleted_at IS NULL AND t.created_at BETWEEN ? AND ? GROUP BY t.status");$stmt->execute(array_merge($scopeParams,[$fromDate,$toDate]));foreach($stmt->fetchAll() as $row)$statusCounts[$row['status']]=(int)$row['total'];
$stmt=$pdo->prepare("SELECT u.name,u.role,COUNT(DISTINCT t.id) total,SUM(t.status='approved') completed FROM task_assignees ta JOIN users u ON u.id=ta.user_id JOIN tasks t ON t.id=ta.task_id JOIN projects p ON p.id=t.project_id WHERE {$scope} AND t.deleted_at IS NULL AND t.created_at BETWEEN ? AND ? GROUP BY u.id ORDER BY total DESC,u.name LIMIT 8");$stmt->execute(array_merge($scopeParams,[$fromDate,$toDate]));$workload=$stmt->fetchAll();$workloadMax=max(1,...array_map(fn($row)=>(int)$row['total'],$workload));
$trendStart=$fromDate;
$trendEnd=$toDate;
$trend=[];
for($i=5;$i>=0;$i--){$key=date('Y-m',strtotime("-{$i} months",strtotime($to)));$trend[$key]=['label'=>date('M',strtotime($key.'-01')),'value'=>0];}
$stmt=$pdo->prepare("SELECT DATE_FORMAT(t.reviewed_at,'%Y-%m') period,COUNT(*) total FROM tasks t JOIN projects p ON p.id=t.project_id WHERE {$scope} AND t.deleted_at IS NULL AND t.status='approved' AND t.reviewed_at BETWEEN ? AND ? GROUP BY period");
$stmt->execute(array_merge($scopeParams,[$trendStart,$trendEnd]));
foreach($stmt->fetchAll() as $row){if(isset($trend[$row['period']]))$trend[$row['period']]['value']=(int)$row['total'];}
$trendMax=max(1,...array_column($trend,'value'));
?>
<div class="additional-page report-page">
 <header class="additional-page-header"><div><p>Report</p><h2>Report & Analytics</h2><span>Pantau performa project, task, deadline, dan produktivitas tim.</span></div><div><?php if(in_array($user['role'],['SUPERADMIN','ADMIN'],true)):?><a href="<?= e(app_url('actions/admin-report.php?from='.$from.'&to='.$to)) ?>">Export Excel</a><?php endif;?><button type="button" onclick="window.print()">Export PDF</button><a href="<?= e(app_url('index.php?page=reports&loading=1')) ?>">Preview Loading</a></div></header>
 <form class="report-date-filter" method="get"><input type="hidden" name="page" value="reports"><label>Dari<input type="date" name="from" value="<?= e($from) ?>"></label><label>Sampai<input type="date" name="to" value="<?= e($to) ?>"></label><button>Terapkan Periode</button><a href="<?= e(app_url('index.php?page=reports')) ?>">Reset</a></form>
 <section class="additional-kpis"><?php foreach([['Total Project',$projects,'blue'],['Task Selesai',$completed,'green'],['Overdue Task',$overdue,'orange'],['Completion Rate',$rate.'%','navy'],['Active User',$activeUsers,'blue']] as [$label,$value,$tone]):?><article class="<?= e($tone) ?>"><i><?= e(strtoupper(substr($label,0,1))) ?></i><span><small><?= e($label) ?></small><b><?= e($value) ?></b><em>Data periode saat ini</em></span></article><?php endforeach;?></section>
 <section class="report-grid"><article class="additional-card report-trend"><header><h3>Task Completion Trend</h3><span><?= e(date('d M',strtotime($from))) ?> - <?= e(date('d M Y',strtotime($to))) ?></span></header><div class="report-line"><?php foreach($trend as $point):$height=$point['value']?max(8,(int)round($point['value']/$trendMax*100)):2;?><i style="--value:<?= e($height) ?>%"><b><?= e($point['value']) ?></b><span><?= e($point['label']) ?></span></i><?php endforeach;?></div></article><article class="additional-card"><header><h3>Task by Status</h3></header><div class="report-donut" style="--done:<?= e($rate) ?>"><b><?= e($tasks) ?><small>Total Task</small></b></div><div class="report-legend"><?php foreach($statusCounts as $status=>$count):?><span><i class="<?= e($status) ?>"></i><?= e(get_task_status_label($status)) ?><b><?= e($count) ?></b></span><?php endforeach;?></div></article><aside class="additional-card report-insights"><h3>Insights & Alerts</h3><p><b><?= e($overdue) ?> Task</b><span>Risiko deadline perlu segera ditindaklanjuti.</span></p><p><b><?= e(count(array_filter($performance,fn($p)=>(int)$p['overdue']>0))) ?> Project</b><span>Project memiliki task overdue.</span></p><p><b><?= e($completed) ?> Selesai</b><span>Task diselesaikan pada periode terpilih.</span></p><a href="<?= e(app_url('index.php?page=deadlines')) ?>">Lihat Detail Deadline</a></aside></section>
 <section class="additional-card report-workload"><header><h3>Workload by Assignee</h3><span>Berdasarkan task pada periode terpilih</span></header><div><?php foreach($workload as $row):$width=max(5,(int)round((int)$row['total']/$workloadMax*100));?><article><i><?= e(strtoupper(substr($row['name'],0,2))) ?></i><span><b><?= e($row['name']) ?></b><small><?= e(role_label($row['role'])) ?> · <?= e($row['completed']) ?> selesai</small><em><u style="width:<?= e($width) ?>%"></u></em></span><strong><?= e($row['total']) ?> task</strong></article><?php endforeach;?><?php if(!$workload):?><div class="additional-empty compact"><i>⌕</i><h3>Data Tidak Ditemukan</h3><p>Belum ada workload assignee pada periode ini.</p></div><?php endif;?></div></section>
 <section class="additional-card report-performance"><header><h3>Project Performance Overview</h3><a href="<?= e(app_url('index.php?page=projects')) ?>">Lihat Semua Project</a></header><div class="additional-table"><table><thead><tr><th>Project</th><th>Manager</th><th>Total Task</th><th>Completed</th><th>Overdue</th><th>Progress</th></tr></thead><tbody><?php foreach($performance as $p):$progress=(int)$p['total']?round((int)$p['completed']/(int)$p['total']*100):0;?><tr><td><b><?= e($p['title']) ?></b></td><td><?= e($p['manager']) ?></td><td><?= e($p['total']) ?></td><td><?= e($p['completed']) ?></td><td><?= e($p['overdue']) ?></td><td><span class="additional-progress"><i style="width:<?= e($progress) ?>%"></i></span><b><?= e($progress) ?>%</b></td></tr><?php endforeach;?><?php if(!$performance):?><tr><td colspan="6"><div class="additional-empty"><i>⌕</i><h3>Data Tidak Ditemukan</h3><p>Belum ada data performa project yang dapat ditampilkan.</p><a href="<?= e(app_url('index.php?page=projects')) ?>">Buka Project</a></div></td></tr><?php endif;?></tbody></table></div></section>
</div>
