<?php
$catalog=[
 ['id'=>1,'name'=>'Pembangunan Aplikasi Web','description'=>'Template standar project pengembangan aplikasi web','type'=>'project','category'=>'IT & Software','department'=>'PDSI','tasks'=>32,'checklists'=>12,'status'=>'active'],
 ['id'=>2,'name'=>'Riset & Penelitian Akademik','description'=>'Template kegiatan riset dan penelitian','type'=>'project','category'=>'Research','department'=>'LPPM','tasks'=>27,'checklists'=>9,'status'=>'active'],
 ['id'=>3,'name'=>'Kampanye Marketing Digital','description'=>'Template kampanye digital end-to-end','type'=>'project','category'=>'Marketing','department'=>'PMB','tasks'=>25,'checklists'=>8,'status'=>'active'],
 ['id'=>4,'name'=>'Desain Brand Identity','description'=>'Proses lengkap desain identitas brand','type'=>'task','category'=>'Design','department'=>'Humas','tasks'=>18,'checklists'=>6,'status'=>'draft'],
 ['id'=>5,'name'=>'Proyek Konstruksi Gedung','description'=>'Template manajemen proyek konstruksi','type'=>'project','category'=>'Construction','department'=>'Sarpras','tasks'=>41,'checklists'=>15,'status'=>'active'],
 ['id'=>6,'name'=>'Implementasi ERP','description'=>'Template implementasi sistem ERP','type'=>'task','category'=>'IT & Software','department'=>'PDSI','tasks'=>36,'checklists'=>14,'status'=>'active'],
];
$q=strtolower(trim($_GET['q']??''));$type=$_GET['type']??'all';$status=$_GET['status']??'all';$department=$_GET['department']??'all';$selectedId=(int)($_GET['preview']??0);
$templates=array_values(array_filter($catalog,function($t)use($q,$type,$status,$department){return (!$q||str_contains(strtolower(implode(' ',$t)),$q))&&($type==='all'||$t['type']===$type)&&($status==='all'||$t['status']===$status)&&($department==='all'||$t['department']===$department);}));
$selected=$selectedId?current(array_filter($catalog,fn($t)=>$t['id']===$selectedId)):null;
$counts=['total'=>count($catalog),'project'=>count(array_filter($catalog,fn($t)=>$t['type']==='project')),'task'=>count(array_filter($catalog,fn($t)=>$t['type']==='task')),'active'=>count(array_filter($catalog,fn($t)=>$t['status']==='active')),'draft'=>count(array_filter($catalog,fn($t)=>$t['status']==='draft'))];
$templateUrl=fn(array $changes=[])=>app_url('index.php?'.http_build_query(array_merge(['page'=>'templates','q'=>$q,'type'=>$type,'status'=>$status,'department'=>$department],$changes)));
?>
<div class="additional-page template-page">
 <header class="additional-page-header"><div><p>Management</p><h2>Template Management</h2><span>Kelola template project dan task untuk mempercepat workflow tim.</span></div><div><button type="button" data-open-small-modal>+ Buat Template Baru</button></div></header>
 <section class="additional-kpis"><?php foreach([['Total Template',$counts['total'],'blue'],['Project Template',$counts['project'],'navy'],['Task Template',$counts['task'],'orange'],['Active Template',$counts['active'],'green'],['Draft Template',$counts['draft'],'blue']] as [$label,$value,$tone]):?><article class="<?= e($tone) ?>"><i><?= e(substr($label,0,1)) ?></i><span><small><?= e($label) ?></small><b><?= e($value) ?></b><em>Katalog UI saat ini</em></span></article><?php endforeach;?></section>
 <section class="template-tabs"><a class="<?= $type==='all'?'active':'' ?>" href="<?= e($templateUrl(['type'=>'all'])) ?>">Semua Template</a><a class="<?= $type==='project'?'active':'' ?>" href="<?= e($templateUrl(['type'=>'project'])) ?>">Project Templates</a><a class="<?= $type==='task'?'active':'' ?>" href="<?= e($templateUrl(['type'=>'task'])) ?>">Task Templates</a></section>
 <form class="additional-filter" method="get"><input type="hidden" name="page" value="templates"><label>⌕ <input name="q" value="<?= e($q) ?>" placeholder="Cari template..."></label><select name="type"><option value="all">Semua Tipe</option><option value="project" <?= $type==='project'?'selected':'' ?>>Project</option><option value="task" <?= $type==='task'?'selected':'' ?>>Task</option></select><select name="status"><option value="all">Semua Status</option><option value="active" <?= $status==='active'?'selected':'' ?>>Active</option><option value="draft" <?= $status==='draft'?'selected':'' ?>>Draft</option></select><select name="department"><option value="all">Semua Department</option><?php foreach(array_unique(array_column($catalog,'department')) as $d):?><option <?= $department===$d?'selected':'' ?>><?= e($d) ?></option><?php endforeach;?></select><button>Filter</button><a href="<?= e(app_url('index.php?page=templates')) ?>">Reset</a></form>
 <section class="template-layout"><aside class="additional-card template-categories"><h3>Categories</h3><?php foreach(array_count_values(array_column($catalog,'category')) as $label=>$count):?><span><b><?= e($label) ?></b><em><?= e($count) ?></em></span><?php endforeach;?><p>Template Management masih berupa katalog UI karena backend existing belum memiliki workflow template. Tidak ada data database yang diubah.</p></aside><section class="additional-card template-table"><div class="additional-table"><table><thead><tr><th>Template</th><th>Type / Category</th><th>Department</th><th>Tasks</th><th>Checklists</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($templates as $t):?><tr><td><b><?= e($t['name']) ?></b><small><?= e($t['description']) ?></small></td><td><span class="template-category"><?= e(ucfirst($t['type']).' · '.$t['category']) ?></span></td><td><?= e($t['department']) ?></td><td><?= e($t['tasks']) ?></td><td><?= e($t['checklists']) ?></td><td><?= status_badge($t['status']) ?></td><td><a class="template-action" href="<?= e($templateUrl(['preview'=>$t['id']])) ?>">Preview</a></td></tr><?php endforeach;?><?php if(!$templates):?><tr><td colspan="7"><div class="additional-empty"><i>⌕</i><h3>Data Tidak Ditemukan</h3><p>Template yang sesuai filter belum tersedia.</p><a href="<?= e(app_url('index.php?page=templates')) ?>">Reset Filter</a></div></td></tr><?php endif;?></tbody></table></div></section></section>
 <?php if($selected):?><section class="additional-card template-preview"><header><div><h3><?= e($selected['name']) ?></h3><span><?= e($selected['description']) ?></span></div><a href="<?= e($templateUrl(['preview'=>0])) ?>">Tutup Preview</a></header><div><p><b>Tipe</b><span><?= e(ucfirst($selected['type'])) ?></span></p><p><b>Kategori</b><span><?= e($selected['category']) ?></span></p><p><b>Department</b><span><?= e($selected['department']) ?></span></p><p><b>Default Task</b><span><?= e($selected['tasks']) ?> task</span></p><p><b>Checklist</b><span><?= e($selected['checklists']) ?> item</span></p></div></section><?php endif;?>
 <button class="additional-fab" type="button" data-open-small-modal>+</button>
</div>
<div class="small-modal-overlay" data-small-modal><section class="small-modal-panel"><i></i><header><div><p>Prototype UI</p><h3>Buat Template Baru</h3><span>Form ditampilkan sebagai preview karena backend existing belum memiliki workflow template.</span></div><button type="button" data-close-small-modal>×</button></header><form><label>Nama Template<input required placeholder="Masukkan nama template"></label><label>Tipe<select><option>Project Template</option><option>Task Template</option></select></label><label>Kategori<input placeholder="Contoh: IT & Software"></label><label>Deskripsi<textarea rows="3" placeholder="Deskripsi singkat template"></textarea></label><footer><button type="button" data-close-small-modal>Batal</button><button type="button" data-close-small-modal>Tutup Preview</button></footer></form></section></div>
<script>(()=>{const modal=document.querySelector('[data-small-modal]');document.querySelectorAll('[data-open-small-modal]').forEach(b=>b.addEventListener('click',()=>modal?.classList.add('open')));document.querySelectorAll('[data-close-small-modal]').forEach(b=>b.addEventListener('click',()=>modal?.classList.remove('open')));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')})})();</script>
